language: go

go:
  - 1.5
  - 1.6
  - 1.7
  - tip

matrix:
  allow_failures:
    - go: tip

install:
  - go get -d -v ./... && go build -v ./...
  - go get -u github.com/stretchr/testify/assert

script:
  - go test ./...
